language: cpp

env:
  global:
    - NVS_VERSION=1.4.2
    - NODEJS_VERSION=node/8

os:
  - osx
  - linux

compiler:
  - gcc

dist: trusty
sudo: false
addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell
      - gdb

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
    else
      brew tap caskroom/cask       || exit 2
      brew cask install powershell || exit 2
    fi
    git clone --branch v$NVS_VERSION --depth 1 https://github.com/jasongin/nvs ~/.nvs
    . ~/.nvs/nvs.sh
    nvs --version
    nvs add $NODEJS_VERSION
    nvs use $NODEJS_VERSION
    node --version
    npm --version

script: pwsh -NonInteractive -NoProfile -NoLogo scripts/ci.ps1

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/064f3494f67de1248aa0
    - https://webhooks.gitter.im/e/cfff11fc076f431c1edf
  email:
    on_success: change
    on_failure: always
